pipeline: nac

data_dir: data
results_dir: exp/nac_anon
scp_name: wav.scp

model:
  checkpoint_dir: ~/.local/share/tts/tts_models--multilingual--multi-dataset--bark
  voice_dir: anonymization/modules/nac/suno_voices/v2

datasets:
  - name: IEMOCAP_dev
    data: IEMOCAP_dev
  - name: IEMOCAP_test
    data: IEMOCAP_test
  - name: libri_dev
    data: libri_dev
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: libri_test
    data: libri_test
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: train-clean-360
    data: train-clean-360

speaker_mappings_root: anonymization/modules/nac/speaker_mappings