pipeline: nac

data_dir: data

model:
  checkpoint_dir: ~/.local/share/tts/tts_models--multilingual--multi-dataset--bark
  voice_dir: anonymization/modules/nac/suno_voices/v2

datasets:
  - name: libri_dev
    data: libri_dev
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: libri_test
    data: libri_test
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: train-clean-360
    data: train-clean-360